### ISSUE TITLE
关于常量池

### ISSUE THREAD

**Issue by bfchengnuo** [bfchengnuo/MyRecord#3]
所谓常量池，就是存储常量的地方，最常见的常量就是我们用 final 修饰的，和 static 一起用那么就是静态常量了。

常量池主要**用于存放**两大类常量：
- 字面量 (Literal)
    字面量相当于 Java 语言层面常量的概念，如文本字符串，声明为 final 的常量值等
- 符号引用量 (Symbolic References)
    符号引用则属于编译原理方面的概念，包括了如下三种类型的常量：类和接口的全限定名、字段名称和描述符、方法名称和描述符。

Java 中的常量池，还可以分为**两种形态**：
- 静态常量池
    所谓静态常量池，即 `*.class` 文件中的常量池，class 文件中的常量池不仅仅包含字符串(数字)字面量，还包含类、方法的信息，占用 class 文件绝大部分空间。
- 运行时常量池
    而运行时常量池，则是 jvm 虚拟机在完成类装载操作后，将 class 文件中的常量池载入到内存中，并保存在方法区中，我们常说的常量池，就是指方法区中的运行时常量池。

运行时常量池相对于 class 文件常量池的另外一个重要特征是具备**动态性**，Java 语言并不要求常量一定只有编译期才能产生，也就是并非预置入 class 文件中常量池的内容才能进入方法区运行时常量池，运行期间也可能将新的常量放入池中，这种特性被开发人员利用比较多的就是 String 类的 intern() 方法。

---

java 中基本类型的包装类的大部分都实现了常量池技术，这些类是:
Byte、Short、Integer、Long、Character、Boolean
另外两种浮点数类型的包装类则没有实现。
这5种包装类默认创建了数值 **[-128，127]** 的相应类型的缓存数据，但是超出此范围仍然会去创建新的对象。

**Comment by bfchengnuo** [comment]
想要理解常量池，必须要关注编译期的行为，只有这样才能更好的理解常量池。
对于这一点，详细解剖可去看看《深入理解 JVM》

运行时常量池中的常量，基本来源于各个 class 文件中的常量池（比如各个 class 中程序员定义的常量）。

**程序运行时（后）**，除非手动向常量池中添加常量(比如调用 intern 方法)，否则 jvm 不会自动添加常量到常量池。
PS：数值类型的常量池不可以手动添加常量，程序启动时常量池中的常量就已经确定了。

关于位置，对于 HotSpot 常量池在方法区，到 JDK7 中常量池移动到了堆中（运行时常量池还是在方法区），但是在逻辑上是独立的。
在 JDK8 中，移除了方法区，转而用 Metaspace 区域替代，那么自然运行时常量池是划分在 Metaspace 区域中。

**Comment by bfchengnuo** [comment]
## Java中的字符串常量池

字符串常量池应该是最喜闻乐见的，很多人都着重在讨论这个，笔试面试也很喜欢考这个。

Java中字符串对象创建有两种形式，一种为字面量形式（双引号直接赋值），另一种就是使用new这种标准的构造对象的方法。

> 当代码中出现字面量形式创建字符串对象时，JVM首先会对这个字面量进行检查，如果字符串常量池中存在相同内容的字符串对象的引用，则将这个引用返回，否则新的字符串对象被创建，然后将这个引用放入字符串常量池，并返回该引用。
>
> [小黑屋](https://droidyue.com/blog/2014/12/21/string-literal-pool-in-java/) 对其工作原理的解释

对于字面量形式：首先查找字符串常量池，如果没有找到就创建这个字符串对象，然后加入到字符串常量池，然后再返回这个地址。
第二次查找时，找到立即返回其地址。

---
使用 new 创建：不管常量池有没有相同内容的对象都会创建。

---
intern 方法：首先检查字符串常量池中是否有该对象的引用，如果存在，则将这个引用返回给变量，否则将引用加入并返回给变量。
这个和第一种是有些许区别的，仔细看描述。

---
解释：
- 字符串常量池存放的是对象引用，不是对象
    字符串中实际内容对象是 char[]
- 随着弱引用的加入，字符串常量池中持有的共享字符串引用（比如通过 intern 加入的），GC 无法回收的问题得已解决
- 当你确定某个字符串会频繁使用多次的时候，可以使用 intern 来优化
- 由于 == 比 equals() 快，引入字符串常量池也算是提高了效率
- 据说，Java 默认只会预先缓存一个字符串常量，那就是 “Java”

> 对象还是引用的问题，还需要区分 JDK 版本来看，7 以前，字符串常量存储在 JVM 的永久区(Perm)，那么要求其中必须存储的是对象本身；
> 而 7 以后，字符串常量被挪到堆内存(Heap)中了，其中存储的就允许是 String 对象的引用了，具体存的对象还是引用，需要看如何声明字符串变量以及对 intern 的使用了。

## 经典问题
String s =new String(“xyz”); 创建了几个 string object？
大多数的答案是说两个，少部分说是不确定，因为不知道之前 “xyz” 是否已经被使用过。
### 一种解释
1. 类加载对一个类只会进行一次。"xyz" 在类加载时就已经创建并驻留了（如果该类被加载之前已经有"xyz"字符串被驻留过则不需要重复创建用于驻留的"xyz"实例）。
    驻留的字符串是放在全局共享的字符串常量池中的。

2. 在这段代码后续被运行的时候，"xyz"字面量对应的String实例已经固定了，不会再被重复创建。
    所以这段代码将常量池中的对象**复制一份**放到 heap 中，并且把 heap 中的这个对象的引用交给 s1 持有。

### 另一种解释
对于这句代码，可分为两个过程：
1. jvm 首先在字符串常量池内里面看看找不找到字符串"xyz"；找到，进入第二步；否则，创建新的 String 对象，并放到字符串常量池里面。
2. 然后由于遇到了 new，还会在堆创建 String 对象，其实是拷贝的常量池的那个，拷贝应该比创建快吧...最后将其返回给 s1。

new String("xyz") ===> new String() 和 "xyz"

**Comment by loliskye** [comment]
关于常量池的几种区分，我看到一篇文章总结的不错，[点我起飞](https://tangxman.github.io/2015/07/27/the-difference-of-java-string-pool/)
